### ISSUE TITLE
Time zone issue in ExpiringKeystoreHealthCheckTest causes failures

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/dropwizard-service-utilities#104]
It is about 7:30pm EST on Mar 19, 2021 and I was just running the tests. Three in `ExpiringKeystoreHealthCheckTest` unexpectedly failed:

* ShouldReportHealthy / whenThereAreOnlyValidCerts
* ShouldReportUnhealthy / whenThereAreExpiredCerts
* ShouldReportUnhealthy / whenThereAreExpiringCerts

All three have multiple failures on `issuedOn` and `expiresOn` dates (corresponding to `notBefore` and `notAfter` in `X509Certificate`, respectively).

Since they're all basically the same problem, here's the output from the `whenThereAreOnlyValidCerts` test for the `issuedOn` check:

```
java.lang.AssertionError: 
Expecting:
  "Tue, 19 Jan 2021 00:26:10 GMT"
to start with:
  "Mon, 18 Jan 2021"
```

and for the `expiresOn` check:

```
java.lang.AssertionError: 
Expecting:
  "Sun, 11 Sep 2022 00:26:10 GMT"
to start with:
  "Sat, 10 Sep 2022"
```

It certainly appears we have a problem with time zones, though I am not sure if this is limited only to the tests or if there is an actual problem with the code. Since running the tests when local time and UTC are on the same day works fine, I am _speculating_ it is a problem with the tests. But don't quote me on that.

**Comment by sleberknight** [comment]
Using `keytool` on a temporary keystone file created during the test (I breakpointed the test) you see the following:

```
Valid from: Mon Jan 18 19:38:53 EST 2021 until: Wed Feb 17 19:38:53 EST 2021
```

So the certificate's listed time zone is EST (since that's my default zone). So, we probably just need to make the tests smarter and agnostic of the time zone.

**Comment by sleberknight** [comment]
I just tried running the tests again locally on my MacBook at about 10:30 PM EST and they now pass. I kind of expected them to fail until we passed midnight EST time, so not sure why they pass now...

**Comment by chrisrohr** [comment]
They pass at 9:23 PM EST as well.  I'm guessing this only happens for a single hour and is an EST versus EDT issue.

**Comment by chrisrohr** [comment]
In fact I just did a bit more looking... right now on 3/23 1900 ET = 2300 UTC.  We take the issuedOn from the cert and convert it using `DateTimeFormatter.RFC_1123_DATE_TIME` using the UTC time zone.  I think this is causing the date to be on at 0000 the next day because it is not taking into account daylight savings.

**Comment by chrisrohr** [comment]
This is definitely an EDT versus EST issue and differences between the `DateTimeFormatter` used between the test and the production code.  We have 2 options here:

1. In the test we can use the `DateTimeFormatterBuilder` to "copy" the `DateTimeFormatter#RFC_1123_DATE_TIME` format and strip off the time parts to get the date part to compare against.
2. In `BasicCertInfo` we stop storing `issuedOn` and `expiresOn` as strings and store them as some flavor of the Date/Time API. `X509Certificate` returns `Date` instances, and currently we convert to `Instance` and then to a String.  **This option would break the API**
