### ISSUE TITLE
JobSchedule de-serialization should respect the default initial delay

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/dropwizard-service-utilities#422]
If you de-serialize `JobSchedule` from JSON or YAML, and do not provide an initial delay, the resulting instance has a `null` value for `initialDelay`, which should never happen. But today it _did_ happen to me when  I was changing some configuration on a service in order to test some things.

This happens because `JobSchedule` has Lombok annotations on it for `@Builder`, `@NoArgsConstructor` and `@AllArgsConstructor`. Unfortunately, while the no-args constructor and the generated builder code respect the default value for `initialDelay`, the all-args constructor does not. This is true when there is only an `@Builder` annotation or whether using `@AllArgsConstructor`, i.e., the generated constructor looks like:

```java
@java.beans.ConstructorProperties({ "initialDelay", "intervalDelay" })
JobSchedule(Duration initialDelay, Duration intervalDelay) {
    this.initialDelay = initialDelay;
    this.intervalDelay = intervalDelay;
}
```

Therefore, when a de-serializer (Jackson) de-serializes from JSON or YAML using the all-args constructor, and there is no value specified for `initialDelay`, it results in a `null` value.

To make this work one would expect, we unfortunately need to add an all-args constructor which sets a default `initialDelay` if necessary. And, we need to move the `@Builder` to this constructor. So inside this constructor, we'll need to do something like:

```java
this.initialDelay = isNull(initialDelay) ? DEFAULT_INITIAL_DELAY : initialDelay;
```

This negates Lombok's code generation, but it needs to work as you would expect.

**Comment by sleberknight** [comment]
I am pretty sure this could also be solved by adding Lombok's `@Jacksonized` annotation to the class, which clearly would only work with Jackson de-serialization. In this case, only the `@Jacksonized` annotation needs to be added.

However, `@Jacksonized` is an _experimental_ Lombok feature, which makes me a bit uneasy using it. (And of course some would say never use Lombok in the first place, but whatever.) So, in addition to the fact that `@Jacksonized` only works with Jackson, and it is experimental, makes me think we should (for now) just use the explicit constructor.

**Comment by chrisrohr** [comment]
I suggest using Jacksonized for now. Most of kiwi right now depends on Jackson and it is the cleaner fix with that assumption.

**Comment by sleberknight** [comment]
And in addition this is a Dropwizard-specific library so of course it uses Jackson!
