### ISSUE TITLE
Handle Hibernate classes in LoggingExceptionMapper

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/dropwizard-service-utilities#48]
If we are doing this shenanigans for Spring classes, then we probably should also do it for Hibernate, especially since we removed Spring from most services that are using Hibernate and are just using Dropwizard's native Hibernate support.

However, I suggest adding a new issue to add this functionality instead of doing it here.

_Originally posted by @sleberknight in https://github.com/kiwiproject/dropwizard-service-utilities/pull/37#discussion_r538862078_

**Comment by chrisrohr** [comment]
@sleberknight What packages specifically do you want to handle?

**Comment by sleberknight** [comment]
For now, these:

* `org.hibernate.dialect.lock.OptimisticEntityLockException`
* `org.hibernate.exception.ConstraintViolationException`
